export const DUMMY_JOBS = [
  {
    id: 1,
    company: 'Amazon',
    jobTitle: 'Senior Designer',
    datePosted: '20 May, 2023',
    logo: 'assets/amazon-logo.svg',
    isSaved: true,
    tags: ['Part time', 'Senior Level', 'Remote'],
    rates: { frequency: 'hr', amount: 160 },
    country: 'San Francisco',
    color: 'bg-[#FF5733]/20',
  },
  {
    id: 2,
    company: 'Google',
    jobTitle: 'Software Engineer',
    datePosted: '12 April, 2023',
    logo: 'assets/google-logo.svg',
    isSaved: false,
    tags: ['Full time', 'Mid Level', 'Onsite'],
    rates: { frequency: 'mth', amount: 9000 },
    country: 'Mountain View',
    color: 'bg-[#33FF57]/20',
  },
  {
    id: 3,
    company: 'Microsoft',
    jobTitle: 'Cloud Architect',
    datePosted: '05 June, 2023',
    logo: 'assets/microsoft-logo.svg',
    isSaved: true,
    tags: ['Contract', 'Senior Level', 'Remote'],
    rates: { frequency: 'yr', amount: 150000 },
    country: 'Redmond',
    color: 'bg-[#3375FF]/20',
  },
  {
    id: 4,
    company: 'Tesla',
    jobTitle: 'Data Scientist',
    datePosted: '30 March, 2023',
    logo: 'assets/tesla-logo.svg',
    isSaved: false,
    tags: ['Part time', 'Junior Level', 'Hybrid'],
    rates: { frequency: 'hr', amount: 90 },
    country: 'Palo Alto',
    color: 'bg-[#FF33A1]/20',
  },
  {
    id: 5,
    company: 'Apple',
    jobTitle: 'UX Researcher',
    datePosted: '15 July, 2023',
    logo: 'assets/apple-logo.svg',
    isSaved: true,
    tags: ['Full time', 'Senior Level', 'Remote'],
    rates: { frequency: 'mth', amount: 10500 },
    country: 'Cupertino',
    color: 'bg-[#FFC733]/20',
  },
  {
    id: 6,
    company: 'Facebook',
    jobTitle: 'Backend Engineer',
    datePosted: '08 August, 2023',
    logo: 'assets/facebook-logo.svg',
    isSaved: false,
    tags: ['Contract', 'Mid Level', 'Onsite'],
    rates: { frequency: 'yr', amount: 120000 },
    country: 'Menlo Park',
    color: 'bg-[#FF5733]/20',
  },
  {
    id: 7,
    company: 'Netflix',
    jobTitle: 'DevOps Engineer',
    datePosted: '22 September, 2023',
    logo: 'assets/netflix-logo.svg',
    isSaved: true,
    tags: ['Part time', 'Senior Level', 'Remote'],
    rates: { frequency: 'hr', amount: 140 },
    country: 'Los Gatos',
    color: 'bg-[#33FFF5]/20',
  },
  {
    id: 8,
    company: 'Spotify',
    jobTitle: 'Full Stack Developer',
    datePosted: '03 October, 2023',
    logo: 'assets/spotify-logo.svg',
    isSaved: false,
    tags: ['Full time', 'Mid Level', 'Remote'],
    rates: { frequency: 'mth', amount: 8500 },
    country: 'New York',
    color: 'bg-[#FF5733]/20',
  },
  {
    id: 9,
    company: 'LinkedIn',
    jobTitle: 'Product Manager',
    datePosted: '14 November, 2023',
    logo: 'assets/linkedin-logo.svg',
    isSaved: true,
    tags: ['Full time', 'Senior Level', 'Onsite'],
    rates: { frequency: 'yr', amount: 135000 },
    country: 'Sunnyvale',
    color: 'bg-[#FF33C1]/20',
  },
];
